config/routes.rb
Rails.application.routes.draw do
  resources :recipes

  root :to => "recipes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord

  def ingredients_array
    ingredients.split(">> ").reject(&:blank?)
  end

  def instructions_array
    instructions.split(">> ").reject(&:blank?)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:title, :subtitle, :description, :image, :tags, :serves, :time, :difficulty, :ingredients, :instructions, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kiflica</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="container-fluid">

  <!-- Image and text -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href= "../../recipes#index">Kiflica</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="../../recipes/new">Create <span class="sr-only">(current)</span></a>
        </li>
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Features</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link" href="#">Pricing</a>-->
<!--        </li>-->
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" href="#">Disabled</a>-->
<!--        </li>-->
      </ul>
    </div>
  </nav>

</div>

<div class="container mt-4">
  <%= yield %>
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :recipe_title %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle, id: :recipe_subtitle %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :recipe_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_area :image, id: :recipe_image %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_area :tags, id: :recipe_tags %>
  </div>

  <div class="field">
    <%= form.label :serves %>
    <%= form.number_field :serves, id: :recipe_serves %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.number_field :time, id: :recipe_time %>
  </div>

  <div class="field">
    <%= form.label :difficulty %>
    <%= form.number_field :difficulty, id: :recipe_difficulty %>
  </div>

  <div class="field">
    <%= form.label :ingredients %>
    <%= form.text_area :ingredients, id: :recipe_ingredients %>
  </div>

  <div class="field">
    <%= form.label :instructions %>
    <%= form.text_area :instructions, id: :recipe_instructions %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active, id: :recipe_active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<%# 1 + 1 %>
<%#= 2 + 2  %>

<div class="row">

  <% @recipes.each do |recipe| %>

    <div class="col-xs-12 col-sm-6 col-md-4 my-2">

      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="<%= recipe.image %>" alt="Card image cap">
        <div class="card-body">
<!--          <a href="" title="<%#= recipe.title%>"><h5 class="card-title"><%#= recipe.title[0..20]+"..." %></h5></a>-->
<!--          <a href="" title="<%#= recipe.subtitle.downcase.capitalize%>"><p class="card-text"><%#= recipe.subtitle.downcase.capitalize[0..30]+"..." %></p></a>-->

          <h5 class="card-title"><%= recipe.title%></h5>
          <p class="card-text"><%= recipe.subtitle.downcase.capitalize%></p>


          <a href="<%= recipe_path(recipe) %>" class="btn btn-primary">View</a>
          <!--          <a href="/recipes/<%#= recipe.id %>" class="btn btn-primary">View</a>-->

          <a href="<%= recipe_path(recipe) + "/edit" %>" class="btn btn-primary">Edit</a>


        </div>
      </div>

    </div>

  <% end %>

</div>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<div class="row">

  <div class="col-md-4">
    <div class="card">
      <img class="card-img-top" src="<%= @recipe.image %>" alt="Card image cap">
    </div>
  </div>

  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title"><%= @recipe.title %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= @recipe.subtitle %></h6>
        <hr>
        <p class="card-text"><%= @recipe.description %></p>
        <hr>
        <p class="card-text">
        <div class="">
          <strong>Serves</strong> <%= @recipe.serves %>
        </div>

        <div class="">
          <strong>Cooks in</strong> <%= @recipe.time %>
        </div>
        <div class="">
          <strong>Difficulty</strong> <%= @recipe.difficulty %>
        </div>

        </p>

        <hr>
        <p class="card-text">
          <% @recipe.tags.split(',').each do |tag| %>
            <span class="badge badge-success"> <%= tag %></span>
          <% end %>
        </p>


      </div>
    </div>
  </div>

</div>

<div class="row">

  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Ingredients</h5>

        <ul class="list-group list-group-flush">
          <% @recipe.ingredients_array.each do |ingredient| %>
            <li class="list-group-item"><%= ingredient %></li>
          <% end %>
        </ul>

      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">Method</h5>
        <ol class="">
          <% @recipe.instructions_array.each do |instruction| %>
            <li class=""><%= instruction %></li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>

</div>